  #spring.application.name=shop
  #spring.datasource.url=jdbc:postgresql://localhost:5433/shop_01
  #spring.datasource.username=my_user
  #spring.datasource.password=pass1234
  #spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shop_01
    username: my_user
    password: pass1234
    driver-class-name: org.postgresql.Driver

  application:
    name: Shop

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

server:
  servlet:
    context-path: /api

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}


logging:
  level:
    liquibase: DEBUG

